##### 公共 配置 #######

#内置Tomcat容器配置
server:
  port: 8088
  servlet:
    #应用路径，配置应用路径，可方便进行反向代理
    context-path:
#    context-path: /baseadmin
#基础配置
spring:
  profiles:
    active: ${BASE_ADMIN:dev} #选择配置分支，先读取系统环境变量，如果没有则默认值为 dev
  application:
    name: base-admin

  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/view/

  #mvc接收参数时对日期进行格式化
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  #jackson对响应回去的日期参数进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #打印SQL
  jpa:
    show-sql: true

  #文件传输限制大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#是否需要输入验证码
captcha:
  enable: false

---
##### dev 配置 #######
spring:
  profiles: dev

  #数据库配置
  datasource:
    url: jdbc:mysql://43.143.201.195:3306/medicine?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: Yunding@%#1104
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

#是否需要输入验证码
captcha:
  enable: false

---
##### prod 配置 #######
spring:
  profiles: prod

  #数据库配置
  datasource:
    url: jdbc:mysql://43.143.201.195:3306/medicine?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: Yunding@%#1104
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: true


